.TH GETTUBE 1 "MAY 2010" Linux "User Manuals"
.SH NAME
gettube \- YouTube video downloader
.SH SYNOPSIS
.B gettube [
.I OPTIONS
.B ] URLs
.SH DESCRIPTION
.B gettube
is a Python/Gtk2 program which allows you to download YouTube videos in various formats.
.SH OPTIONS
.IP "-h, --help"
show this help message and exit
.IP "-v, --version"
Show version information
.IP "-g, --gui"
GUI mode
.IP "-f FORMAT"
Select download format. FORMAT can be FLV, 3GP, MP4, MP4-720p, MP4-1080p, default MP4.
.SH BUGS
Please report all bugs at http://github.com/Aitjcize/gettube/issues
.SH AUTHOR
Wei-Ning Huang (AZ) <aitjcize@gmail.com>
